---
- hosts: logger
  vars_files:
   - vars/default.yml
  roles:
    - { role: rsyslog-server, tags: ["rsyslog-server"] }
    - { role: redis, tags: ["redis"] }
    - { role: elasticsearch, tags: ["elasticsearch"] }
    - { role: logstash, tags: ["logstash"] }
    - { role: supervisord, tags: ["supervisor"] }
    - { role: apache-kibana, tags: ["apache-kibana"] }
    - { role: shorewall, tags: ["shorewall"] }
##
## At this moment Shorewall is available only for Debian role.
## I'm working to estend the role to CentOS too
